=== Hassane31/Data-semi-structuree-/TP 2 /listeAdresses.dtd
<!ELEMENT listeAdresses (adresse+)>

<!ELEMENT adresse (nomComplet, num, rue, ville, cp)>
<!ATTLIST adresse categorie (personnelle|professionnelle) #REQUIRED>

<!ELEMENT nomComplet (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

=== Hassane31/Data-semi-structuree-/TP 2 /XML bien formé.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listeAdresses SYSTEM "listeAdresses.dtd">
<listeAdresses>

    <adresse categorie="personnelle">
        <nomComplet>Ahmed Kateb</nomComplet>
        <num>121</num>
        <rue>Plein-Ciel</rue>
        <ville>Oran</ville>
        <cp>31000</cp>
    </adresse>

    <adresse categorie="professionnelle">
        <nomComplet>Sonelgaz</nomComplet>
        <num>12</num>
        <rue>Es-Senia</rue>
        <ville>Oran</ville>
        <cp>31000</cp>
    </adresse>

</listeAdresses>
